### ISSUE TITLE
Add Tax Lot db table schema to Zoning API

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-zoning-api#2]
# Description

- [ ] A schema exists that reflects the tax lot table in [Data Engineering #302](https://github.com/NYCPlanning/data-engineering/issues/302)

# Related
- Blocked by 
  - [ ] #10 (Spatial types needed)
  - [x] #14 (Foreign key to table needed)
  - [x] #12 (Foreign key to table needed)
